name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: latest
        qemu-version: latest

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Run Buildx
      run: |
        docker buildx build \
          --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
          --output "type=image,push=false" \
          --file ./Dockerfile .
#
#    - name: Customizable Docker Buildx Build
#      uses: zmingxie/docker_buildx@v1.1
#      with:
#        # Tags (comma separated) to apply to the image
#        tag: latest
#        # Name of the image
#        imageName: samba-dc
#        # Name of the Dockerfile
#        dockerFile: Dockerfile
#        # Docker `--build-arg` flags (*comma separated*)
#        # buildArg: # optional, default is none
#        # Indicate if the builded image should be published on Docker HUB
#        publish: true
#        # Platforms (comma separated) that should be used to build the image
#        platform: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
#        # User that will publish the image, if indicated
#        dockerHubUser: ${{ secrets.DOCKER_HUB_USER }}
#        # Password of the dockerHubUser
#        dockerHubPassword: ${{ secrets.DOCKER_HUB_PASS }}
#